/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Citoyen;
  GtkWidget *Administrateur;
  GtkWidget *dialogSuppServ;
  GtkWidget *dialogModifServ;
  GtkWidget *dialogAffectServ;
  GtkWidget *dialogAjoutServ;
  GtkWidget *Login;
  GtkWidget *enregistrer;
  GtkWidget *Moto;
  GtkWidget *RS;
  GtkWidget *Tun;
  GtkWidget *mdp_oublie;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Citoyen = create_Citoyen ();
  gtk_widget_show (Citoyen);
  Administrateur = create_Administrateur ();
  gtk_widget_show (Administrateur);
  dialogSuppServ = create_dialogSuppServ ();
  gtk_widget_show (dialogSuppServ);
  dialogModifServ = create_dialogModifServ ();
  gtk_widget_show (dialogModifServ);
  dialogAffectServ = create_dialogAffectServ ();
  gtk_widget_show (dialogAffectServ);
  dialogAjoutServ = create_dialogAjoutServ ();
  gtk_widget_show (dialogAjoutServ);
  Login = create_Login ();
  gtk_widget_show (Login);
  enregistrer = create_enregistrer ();
  gtk_widget_show (enregistrer);
  Moto = create_Moto ();
  gtk_widget_show (Moto);
  RS = create_RS ();
  gtk_widget_show (RS);
  Tun = create_Tun ();
  gtk_widget_show (Tun);
  mdp_oublie = create_mdp_oublie ();
  gtk_widget_show (mdp_oublie);

  gtk_main ();
  return 0;
}

